version: "2"
services:
    nuki:
#        image: giejay/nuki-bridge
        build:
          context: .
          dockerfile: ./Dockerfile
        environment:
          - PYTHONUNBUFFERED=true
          - FLASK_RUN_PORT=5000
        volumes:
          - ./nuki.cfg:/opt/nuki/nuki.cfg
        privileged: true
        network_mode: host